name: sneakers_hype
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/nike_p6000_blck.jpg
    - assets/images/adidas samba black og.jpeg
    - assets/images/nike_sb_dunk_white_gum.jpg
    - assets/images/nb_550.jpg
    - assets/images/adidas_campus_core_black.jpg
    - assets/images/Nike_alphafly_3_volt_Concord.jpg
    - assets/images/new balance 2002R.jpeg
    - assets/images/adidas zero evo sl white.jpeg
    - assets/images/nb_freshfoam_1080v13.jpg
   